notifications:
  email:
    recipients:
      - rahulavd@uw.edu
    on_success: change
    on_failure: always

language: python

python:
  - "3.5"

branches:
  only:
    - master

sudo: false

install:
  - pip install -r requirements.txt
  - pip install xlrd
  - pip install coveralls
  - pip install nose-exclude
  - conda config --set always_yes yes --set changeps1 no
  - conda create -c https://conda.anaconda.org/rdkit -n my-rdkit-env rdkit
  - source activate my-rdkit-env
  - python setup.py install

script:
  - nosetests --with-doctest --with-coverage --cover-package=smdt --exclude-dir=test/external --exclude-dir=extern --where=smdt

after_success:
    - coveralls